print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/zemann1/Desktop/MIN-452-SP15/AlienBehaviorTesting/Assets/Models/testSpaceship 1.mb"`)
{		
	file -o "/Users/zemann1/Desktop/MIN-452-SP15/AlienBehaviorTesting/Assets/Models/testSpaceship 1.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/zemann1/Desktop/MIN-452-SP15/AlienBehaviorTesting/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/zemann1/Desktop/MIN-452-SP15/AlienBehaviorTesting/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/zemann1/Desktop/MIN-452-SP15/AlienBehaviorTesting/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
